name: scrollable_positioned_list
version: 0.4.0
description: >
  A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/enwi/scrollable_positioned_list
repository: https://github.com/enwi/scrollable_positioned_list
issue_tracker: https://github.com/enwi/scrollable_positioned_list/issues

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
